/// Rủi ro sớm FPD30 theo phân khúc (M11). CHẶN DƯỚI, không phải số cuối cùng: xem vùng mù dữ liệu ở docs/metric_dictionary.md mục M11.
table FPD

	/// Số hợp đồng trong mẫu số FPD30.
	measure 'FPD Base Loans' = SUM(FPD[n_loans])
		formatString: #,##0

	/// Số hợp đồng trễ hạn ngay kỳ trả góp đầu tiên trên 30 ngày.
	measure 'FPD30 Loans' = SUM(FPD[n_fpd30])
		formatString: #,##0

	/// M11. Tỷ lệ FPD30. ĐÂY LÀ CHẶN DƯỚI: dữ liệu chỉ ghi kỳ đã trả nên có thiên lệch sống sót,
	/// vùng mù 77.885 hồ sơ. Không dùng riêng số này để xếp hạng kênh hay sản phẩm.
	measure 'FPD30 Rate' = DIVIDE([FPD30 Loans], [FPD Base Loans])
		formatString: 0.0%

	/// Số hợp đồng được duyệt nhưng không có dòng trả góp nào, tức vùng mù không quan sát được FPD.
	measure 'FPD Blind Spot Loans' = SUM(FPD[n_approved_no_installment])
		formatString: #,##0

	column contract_type
		dataType: string
		isHidden
		sourceColumn: contract_type

	column channel_type
		dataType: string
		isHidden
		sourceColumn: channel_type

	column client_type
		dataType: string
		sourceColumn: client_type

	column yield_group
		dataType: string
		sourceColumn: yield_group

	column n_loans
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_loans

	column n_fpd30
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_fpd30

	/// ẨN có chủ đích: dùng measure [FPD30 Rate].
	column fpd30_rate
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: fpd30_rate

	column n_fpd30_late_rule
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_fpd30_late_rule

	/// ẨN có chủ đích.
	column fpd30_late_rule_rate
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: fpd30_late_rule_rate

	column n_approved_no_installment
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_approved_no_installment

	partition FPD = m
		mode: import
		source =
			let
				// Đọc CSV mart xuất từ DuckDB, ép UTF-8 để giữ dấu tiếng Việt
				#"Đã đọc file CSV" = Csv.Document(
					File.Contents(DataFolder & "\mart_fpd_by_segment.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Đã nâng dòng đầu thành tiêu đề" = Table.PromoteHeaders(#"Đã đọc file CSV", [PromoteAllScalars = true]),
				#"Đã ép kiểu dữ liệu từng cột" = Table.TransformColumnTypes(#"Đã nâng dòng đầu thành tiêu đề", {{"contract_type", type text}, {"channel_type", type text}, {"client_type", type text}, {"yield_group", type text}, {"n_loans", Int64.Type}, {"n_fpd30", Int64.Type}, {"fpd30_rate", type number}, {"n_fpd30_late_rule", Int64.Type}, {"fpd30_late_rule_rate", type number}, {"n_approved_no_installment", Int64.Type}})
			in
				#"Đã ép kiểu dữ liệu từng cột"
