/// Rủi ro sớm FPD30 theo phân khúc (M11), trên hợp đồng đã kích hoạt (có kỳ 1 trong lịch trả gốc).
/// Thẻ quay vòng không có trong mẫu số. Tử số rất mỏng nên không dùng làm trục rủi ro.
table FPD

	/// Số hợp đồng trong mẫu số FPD30.
	measure 'FPD Base Loans' = SUM(FPD[n_loans])
		formatString: #,##0

	/// Số hợp đồng trả chưa đủ 95% kỳ 1 trong 30 ngày sau hạn.
	measure 'FPD30 Loans' = SUM(FPD[n_fpd30])
		formatString: #,##0

	/// M11. Tỷ lệ FPD30 trên hợp đồng đã kích hoạt. Tử số rất mỏng (99 ca toàn danh mục),
	/// không dùng riêng số này để xếp hạng kênh hay sản phẩm.
	measure 'FPD30 Rate' = DIVIDE([FPD30 Loans], [FPD Base Loans])
		formatString: 0.000%

	/// Hồ sơ được duyệt nhưng không có lịch trả, tức không kích hoạt. Không thuộc mẫu số FPD30.
	measure 'Approved Not Activated' = SUM(FPD[n_approved_not_activated])
		formatString: #,##0

	column contract_type
		dataType: string
		isHidden
		sourceColumn: contract_type

	column channel_type
		dataType: string
		isHidden
		sourceColumn: channel_type

	column client_type
		dataType: string
		sourceColumn: client_type

	column yield_group
		dataType: string
		sourceColumn: yield_group

	column n_loans
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_loans

	column n_fpd30
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_fpd30

	/// ẨN có chủ đích: dùng measure [FPD30 Rate].
	column fpd30_rate
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: fpd30_rate

	/// FPD30 theo ngày: có lần trả trễ quá 30 ngày.
	column n_fpd30_late_rule
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_fpd30_late_rule

	/// ẨN có chủ đích.
	column fpd30_late_rule_rate
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: fpd30_late_rule_rate

	/// Duyệt, không có lịch trả.
	column n_approved_not_activated
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_approved_not_activated

	/// Duyệt, có lịch trả, không có dòng kỳ 1.
	column n_approved_scheduled_no_installment
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_approved_scheduled_no_installment

	partition FPD = m
		mode: import
		source =
			let
				// Đọc CSV mart xuất từ DuckDB, ép UTF-8 để giữ dấu tiếng Việt
				#"Đã đọc file CSV" = Csv.Document(
					File.Contents(DataFolder & "\mart_fpd_by_segment.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Đã nâng dòng đầu thành tiêu đề" = Table.PromoteHeaders(#"Đã đọc file CSV", [PromoteAllScalars = true]),
				#"Đã ép kiểu dữ liệu từng cột" = Table.TransformColumnTypes(#"Đã nâng dòng đầu thành tiêu đề", {{"contract_type", type text}, {"channel_type", type text}, {"client_type", type text}, {"yield_group", type text}, {"n_loans", Int64.Type}, {"n_fpd30", Int64.Type}, {"fpd30_rate", type number}, {"n_fpd30_late_rule", Int64.Type}, {"fpd30_late_rule_rate", type number}, {"n_approved_not_activated", Int64.Type}, {"n_approved_scheduled_no_installment", Int64.Type}}, "en-US")
			in
				#"Đã ép kiểu dữ liệu từng cột"
