/// Vintage: tỷ lệ TỪNG quá hạn 30+ theo tuổi hợp đồng (M08). Mẫu số đã loại hợp đồng có cờ is_partial_history.
table Vintage

	/// Số hợp đồng trong mẫu số vintage tại MOB đang lọc.
	measure 'Vintage Loans' = SUM(Vintage[n_loans])
		formatString: #,##0

	/// Số hợp đồng từng quá hạn trên 30 ngày tính đến MOB đang lọc.
	measure 'Ever 30 Plus Loans' = SUM(Vintage[n_ever_30_plus])
		formatString: #,##0

	/// M08. Tỷ lệ từng quá hạn 30+ tại MOB đang lọc. Cộng tử và mẫu trước rồi chia.
	/// Không có bộ lọc MOB thì số này gộp mọi MOB và vô nghĩa, hãy dùng [Ever 30 Plus MOB12].
	measure 'Ever 30 Plus Rate' = DIVIDE([Ever 30 Plus Loans], [Vintage Loans])
		formatString: 0.0%

	/// M08 tại MOB 12, trục rủi ro chính của project.
	/// Cố định đúng mob = 12 bằng CALCULATE nên không phụ thuộc slicer MOB.
	/// Dùng thay FPD30 vì FPD có thiên lệch sống sót.
	measure 'Ever 30 Plus MOB12' = ```
			DIVIDE(
			    CALCULATE(SUM(Vintage[n_ever_30_plus]), Vintage[mob] = 12),
			    CALCULATE(SUM(Vintage[n_loans]), Vintage[mob] = 12)
			)
			```
		formatString: 0.0%

	/// Mẫu số của [Ever 30 Plus MOB12]. Dùng cột này khi đặt cạnh tỷ lệ tại MOB 12:
	/// [Vintage Loans] cộng qua MỌI mob nên lớn hơn nhiều lần và không phải mẫu số của tỷ lệ bên cạnh.
	measure 'Vintage Loans MOB12' = CALCULATE(SUM(Vintage[n_loans]), Vintage[mob] = 12)
		formatString: #,##0

	/// Bản dùng cột DPD có dung sai (SK_DPD_DEF). Chỉ tiêu PHỤ để đối chiếu, không phải trục chính.
	measure 'Ever 30 Plus MOB12 Tolerant' = ```
			DIVIDE(
			    CALCULATE(SUM(Vintage[n_ever_30_plus_tolerant]), Vintage[mob] = 12),
			    CALCULATE(SUM(Vintage[n_loans]), Vintage[mob] = 12)
			)
			```
		formatString: 0.0%

	/// pos_cash hay credit_card, cho biết hợp đồng đến từ bảng nguồn nào.
	column source
		dataType: string
		sourceColumn: source

	column contract_type
		dataType: string
		isHidden
		sourceColumn: contract_type

	column channel_type
		dataType: string
		isHidden
		sourceColumn: channel_type

	column client_type
		dataType: string
		sourceColumn: client_type

	column yield_group
		dataType: string
		sourceColumn: yield_group

	/// Nhóm kỳ hạn.
	column tenor_group
		dataType: string
		sourceColumn: tenor_group

	/// Months on book: hợp đồng đã chạy bao nhiêu tháng.
	column mob
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: mob

	column n_loans
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_loans

	column n_observed_full
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_observed_full

	column n_closed_early
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_closed_early

	column n_ever_30_plus
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_ever_30_plus

	column n_ever_30_plus_tolerant
		dataType: int64
		summarizeBy: sum
		sourceColumn: n_ever_30_plus_tolerant

	/// ẨN có chủ đích: dùng measure [Ever 30 Plus Rate].
	column ever_30_plus_rate
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: ever_30_plus_rate

	/// ẨN có chủ đích.
	column ever_30_plus_rate_tolerant
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: ever_30_plus_rate_tolerant

	partition Vintage = m
		mode: import
		source =
			let
				// Đọc CSV mart xuất từ DuckDB, ép UTF-8 để giữ dấu tiếng Việt
				#"Đã đọc file CSV" = Csv.Document(
					File.Contents(DataFolder & "\mart_vintage.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				#"Đã nâng dòng đầu thành tiêu đề" = Table.PromoteHeaders(#"Đã đọc file CSV", [PromoteAllScalars = true]),
				#"Đã ép kiểu dữ liệu từng cột" = Table.TransformColumnTypes(#"Đã nâng dòng đầu thành tiêu đề", {{"source", type text}, {"contract_type", type text}, {"channel_type", type text}, {"client_type", type text}, {"yield_group", type text}, {"tenor_group", type text}, {"mob", Int64.Type}, {"n_loans", Int64.Type}, {"n_observed_full", Int64.Type}, {"n_closed_early", Int64.Type}, {"n_ever_30_plus", Int64.Type}, {"n_ever_30_plus_tolerant", Int64.Type}, {"ever_30_plus_rate", type number}, {"ever_30_plus_rate_tolerant", type number}})
			in
				#"Đã ép kiểu dữ liệu từng cột"
