/// Vintage: tỷ lệ TỪNG quá hạn 30+ theo tuổi hợp đồng (M08). Mẫu số đã loại hợp đồng có cờ is_partial_history.
table Vintage
	lineageTag: f3d19c8d-02d5-44fd-a6a3-f9498b217d1a

	/// Số hợp đồng trong mẫu số vintage tại MOB đang lọc.
	measure 'Vintage Loans' = SUM(Vintage[n_loans])
		formatString: #,##0
		lineageTag: 1f86bf50-8f0b-461a-85c1-1dbaa80d1a58

	/// Số hợp đồng từng quá hạn trên 30 ngày tính đến MOB đang lọc.
	measure 'Ever 30 Plus Loans' = SUM(Vintage[n_ever_30_plus])
		formatString: #,##0
		lineageTag: e10c0f53-1af8-4ceb-8aa0-172c8ebbd719

	/// M08. Tỷ lệ từng quá hạn 30+ tại MOB đang lọc. Cộng tử và mẫu trước rồi chia.
	/// Không có bộ lọc MOB thì số này gộp mọi MOB và vô nghĩa, hãy dùng [Ever 30 Plus MOB12].
	measure 'Ever 30 Plus Rate' = DIVIDE([Ever 30 Plus Loans], [Vintage Loans])
		formatString: 0.0%
		lineageTag: efff712e-ad06-46dd-8ea5-d72a830adbdf

	/// M08 tại MOB 12, trục rủi ro chính của project.
	/// Cố định đúng mob = 12 bằng CALCULATE nên không phụ thuộc slicer MOB.
	/// Dùng thay FPD30 vì FPD có thiên lệch sống sót.
	measure 'Ever 30 Plus MOB12' =
			DIVIDE(
			    CALCULATE(SUM(Vintage[n_ever_30_plus]), Vintage[mob] = 12),
			    CALCULATE(SUM(Vintage[n_loans]), Vintage[mob] = 12)
			)
		formatString: 0.0%
		lineageTag: 0fbfd3cb-19e3-44cf-8621-600b4047927b

	/// Mẫu số của [Ever 30 Plus MOB12]. Dùng cột này khi đặt cạnh tỷ lệ tại MOB 12:
	/// [Vintage Loans] cộng qua MỌI mob nên lớn hơn nhiều lần và không phải mẫu số của tỷ lệ bên cạnh.
	measure 'Vintage Loans MOB12' = CALCULATE(SUM(Vintage[n_loans]), Vintage[mob] = 12)
		formatString: #,##0
		lineageTag: 3d98ca2d-ff8b-4fc2-89e9-cb0c39ea3cd2

	/// Bản dùng cột DPD có dung sai (SK_DPD_DEF). Chỉ tiêu PHỤ để đối chiếu, không phải trục chính.
	measure 'Ever 30 Plus MOB12 Tolerant' =
			DIVIDE(
			    CALCULATE(SUM(Vintage[n_ever_30_plus_tolerant]), Vintage[mob] = 12),
			    CALCULATE(SUM(Vintage[n_loans]), Vintage[mob] = 12)
			)
		formatString: 0.0%
		lineageTag: 8f7129a9-da2f-4d91-9502-572fae75a671

	/// pos_cash hay credit_card, cho biết hợp đồng đến từ bảng nguồn nào.
	column source
		dataType: string
		lineageTag: 24bad64e-eac7-474c-82d3-35da1b6d6f18
		sourceColumn: source

	column contract_type
		dataType: string
		isHidden
		lineageTag: 1bd9c324-7edb-4996-831d-3bd868528a8c
		sourceColumn: contract_type

	column channel_type
		dataType: string
		isHidden
		lineageTag: 66e0d50d-b10e-4e19-9208-2bef59b0841c
		sourceColumn: channel_type

	column client_type
		dataType: string
		lineageTag: 52455ac6-e832-4be7-a26f-80aa32e208cf
		sourceColumn: client_type

	column yield_group
		dataType: string
		lineageTag: ffbec50b-ca99-439f-8afa-e7d8e2879085
		sourceColumn: yield_group

	/// Nhóm kỳ hạn.
	column tenor_group
		dataType: string
		lineageTag: a14d0760-8224-4f25-b013-54061f83ee1c
		sourceColumn: tenor_group

	/// Months on book: hợp đồng đã chạy bao nhiêu tháng.
	column mob
		dataType: int64
		formatString: 0
		lineageTag: 5716b84a-b0b9-4acf-9ff1-84627c5d783f
		summarizeBy: none
		sourceColumn: mob

	column n_loans
		dataType: int64
		lineageTag: 611ff390-bb8c-443b-a854-c0331b19757e
		summarizeBy: sum
		sourceColumn: n_loans

	column n_observed_full
		dataType: int64
		lineageTag: 5014b0a1-d2dd-41c9-93cf-a07c8bfb5421
		summarizeBy: sum
		sourceColumn: n_observed_full

	column n_closed_early
		dataType: int64
		lineageTag: 545623a8-00bd-4c05-bd63-f47782d2d88b
		summarizeBy: sum
		sourceColumn: n_closed_early

	column n_ever_30_plus
		dataType: int64
		lineageTag: 295f44c7-6cf9-4544-80ef-24e151991e84
		summarizeBy: sum
		sourceColumn: n_ever_30_plus

	column n_ever_30_plus_tolerant
		dataType: int64
		lineageTag: 91767bef-d69c-47c1-b02a-868d835b2995
		summarizeBy: sum
		sourceColumn: n_ever_30_plus_tolerant

	/// ẨN có chủ đích: dùng measure [Ever 30 Plus Rate].
	column ever_30_plus_rate
		dataType: double
		isHidden
		lineageTag: 4e690eac-2e96-4d0c-8d9f-3e7a652599f5
		summarizeBy: none
		sourceColumn: ever_30_plus_rate

	/// ẨN có chủ đích.
	column ever_30_plus_rate_tolerant
		dataType: double
		isHidden
		lineageTag: d43d73af-670c-4077-bbb8-62d982d37755
		summarizeBy: none
		sourceColumn: ever_30_plus_rate_tolerant

	partition Vintage = m
		mode: import
		source =
				let
					// Đọc CSV mart xuất từ DuckDB, ép UTF-8 để giữ dấu tiếng Việt
					#"Đã đọc file CSV" = Csv.Document(
						File.Contents(DataFolder & "\mart_vintage.csv"),
						[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
					),
					#"Đã nâng dòng đầu thành tiêu đề" = Table.PromoteHeaders(#"Đã đọc file CSV", [PromoteAllScalars = true]),
					#"Đã ép kiểu dữ liệu từng cột" = Table.TransformColumnTypes(#"Đã nâng dòng đầu thành tiêu đề", {{"source", type text}, {"contract_type", type text}, {"channel_type", type text}, {"client_type", type text}, {"yield_group", type text}, {"tenor_group", type text}, {"mob", Int64.Type}, {"n_loans", Int64.Type}, {"n_observed_full", Int64.Type}, {"n_closed_early", Int64.Type}, {"n_ever_30_plus", Int64.Type}, {"n_ever_30_plus_tolerant", Int64.Type}, {"ever_30_plus_rate", type number}, {"ever_30_plus_rate_tolerant", type number}})
				in
					#"Đã ép kiểu dữ liệu từng cột"

